// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portfolio" | "/*";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/Portfolio.tsx": {
    id: "pages/Portfolio";
    page: "/portfolio";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Home": typeof import("./app/pages/Home.tsx");
  "pages/Portfolio": typeof import("./app/pages/Portfolio.tsx");
  "pages/NotFound": typeof import("./app/pages/NotFound.tsx");
};